Repository storybookjs/monorepo-release-tooling-prototype, pull requests merged in 2023-06, with the labels that each got.

#37 Build: Enforce PR title
  .github/workflows/danger-js.yml
  scripts/dangerfile.ts
Labels: build

#34 Build: Add pick-patches script
  scripts/package.json
  scripts/release/pick-patches.ts
  scripts/yarn.lock
Labels: build

#43 Release: Support canary PRs
  .github/workflows/canary-release-pr.yml
  scripts/release/publish.ts
Labels: build

#45 Release tooling: Make sure write-changelog works with --patchesOnly
  scripts/release/generate-pr-description.ts
  scripts/release/pick-patches.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-unpicked-prs.ts
Labels: build

#47 Release: Check unreleased, unpicked patches
  scripts/release/generate-pr-description.ts
  scripts/release/unreleased-changes-exists.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/write-changelog.ts
Labels: build

#49 Legal: Change Licence
  LICENSE
Labels: bug, patch

#53 Release: Cleanup scripts
  scripts/__mocks__/simple-git.js
  scripts/release/__tests__/is-pr-frozen.test.ts
  scripts/release/pick-patches.ts
  scripts/release/publish.ts
  scripts/release/utils/__mocks__/get-github-info.js
  scripts/release/utils/get-unpicked-prs.ts
  scripts/release/utils/github-client.ts
Labels: bug, patch

#55 Legal: Fix license
  LICENSE
Labels: maintenance

#58 Release tooling: Label patches script
  scripts/__mocks__/uuid.ts
  scripts/package.json
  scripts/release/label-patches.test.ts
  scripts/release/label-patches.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-github-info.ts
  scripts/release/utils/git-client.ts
  scripts/release/utils/github-client.ts
  scripts/yarn.lock
Labels: build

#59 Release tooling: Label patches to next
  scripts/__mocks__/uuid.ts
  scripts/package.json
  scripts/release/label-patches.test.ts
  scripts/release/label-patches.ts
  scripts/release/utils/get-changes.ts
  scripts/release/utils/get-github-info.ts
  scripts/release/utils/git-client.ts
  scripts/release/utils/github-client.ts
  scripts/yarn.lock
Labels: maintenance

#60 Legal: Fix licence once and for all
  LICENSE
Labels: patch, maintenance

#62 Legal: the 2024 license
  LICENSE
Labels: patch, maintenance
